# Generated by Django 5.1.4 on 2024-12-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='cron',
            field=models.DateTimeField(),
        ),
    ]
