# Generated by Django 5.1.4 on 2024-12-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todomodel_cron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='cron',
            field=models.DateField(),
        ),
    ]
